version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      react:
        patterns:
          - react
          - "@types/react"
      biome:
        patterns:
          - "@biomejs/biome"
      next:
        patterns:
          - next
      tailwind:
        patterns:
          - tailwindcss
          - "@tailwindcss/postcss"
