import { createCards } from '../card.factory';
import { Card, CardActions } from '../cards.type';

const bannerSpearPath = '/banner-spear/abilities';

export const bannerSpearCards: Card[] = createCards([
  { level: 'X', name: 'driving inspiration', actions: { top: CardActions.discard, bottom: CardActions.activeLost },
    availableEnhancements: [
      { type: 'diamond', position: { x: 50, y: 49 } },
      { type: 'summonSquare', position: { x: 60, y: 138 } },
    ],
  },
  { level: 'X', name: 'incendiary throw', actions: { top: CardActions.discard, bottom: CardActions.activeLost },
    availableEnhancements: [
      { type: 'diamond', position: { x: 65, y: 31 } },
      { type: 'summonSquare', position: { x: 63, y: 140 } },
      { type: 'summonSquare', position: { x: 63, y: 154 } },
    ],
  },
  { level: 'X', name: 'resolved courage', actions: { top: CardActions.discard, bottom: CardActions.activeDiscard } },
  { level: 1, name: 'at all costs', actions: { top: CardActions.discard, bottom: CardActions.activeDiscard },
    availableEnhancements: [
      { type: 'summonSquare', position: { x: 64, y: 135 } },
      { type: 'summonSquare', position: { x: 109, y: 135 } },
    ],
  },
  { level: 1, name: 'combined effort', actions: { top: CardActions.discard, bottom: CardActions.discard },
    availableEnhancements: [
      { type: 'circle', position: { x: 46, y: 56 } },
      { type: 'circle', position: { x: 86, y: 132 } },
      { type: 'square', position: { x: 86, y: 166 } },
    ],
  },
  { level: 1, name: 'deflecting maneuver', actions: { top: CardActions.activeDiscard, bottom: CardActions.activeDiscard },
    availableEnhancements: [
      { type: 'circle', position: { x: 85, y: 30 } },
      { type: 'circle', position: { x: 85, y: 136 } },
    ],
  },
  { level: 1, name: 'javelin', actions: { top: CardActions.discard, bottom: CardActions.discard },
    availableEnhancements: [
      { type: 'diamond', position: { x: 66, y: 48 } },
      { type: 'circle', position: { x: 83, y: 135 } },
    ],
  },
  { level: 1, name: 'pincer movement', actions: { top: CardActions.discard, bottom: CardActions.discard },
    availableEnhancements: [
      { type: 'diamond', position: { x: 46, y: 57 } },
      { type: 'circle', position: { x: 84, y: 135 } },
    ],
  },
  { level: 1, name: 'rallying cry', actions: { top: CardActions.discard, bottom: CardActions.activeLost },
    availableEnhancements: [
      { type: 'hex', position: { x: 103, y: 41 } },
      { type: 'summonSquare', position: { x: 60, y: 138 } },
    ],
  },
  { level: 1, name: 'regroup', actions: { top: CardActions.discard, bottom: CardActions.discard },
    availableEnhancements: [
      { type: 'diamondPlus', position: { x: 59, y: 55 } },
      { type: 'square', position: { x: 85, y: 154 } },
    ],
  },
  { level: 1, name: 'set for the charge', actions: { top: CardActions.activeDiscard, bottom: CardActions.discard } },
  { level: 1, name: 'tip of the spear', actions: { top: CardActions.discard, bottom: CardActions.discard },
    availableEnhancements: [
      { type: 'hex', position: { x: 109, y: 28 } },
      { type: 'circle', position: { x: 85, y: 148 } },
    ],
  },
  { level: 1, name: 'unbreakable wall', actions: { top: CardActions.discard, bottom: CardActions.activeLost } },
  { level: 2, name: 'meat grinder', actions: { top: CardActions.discard, bottom: CardActions.discard },
    availableEnhancements: [
      { type: 'diamond', position: { x: 48, y: 54 } },
      { type: 'circle', position: { x: 57, y: 162 } },
    ],
  },
  { level: 2, name: 'pinning charge', actions: { top: CardActions.discard, bottom: CardActions.discard },
    availableEnhancements: [
      { type: 'diamond', position: { x: 66, y: 34 } },
    ],
  },
  { level: 3, name: 'head of the hammer', actions: { top: CardActions.lose, bottom: CardActions.discard },
    availableEnhancements: [
      { type: 'diamond', position: { x: 48, y: 52 } },
      { type: 'circle', position: { x: 85, y: 129 } },
    ],
  },
  { level: 3, name: 'let them come', actions: { top: CardActions.discard, bottom: CardActions.activeLost },
    availableEnhancements: [
      { type: 'summonSquare', position: { x: 58, y: 140 } },
    ],
  },
  { level: 4, name: 'air support', actions: { top: CardActions.discard, bottom: CardActions.activeDiscard },
    availableEnhancements: [
      { type: 'diamond', position: { x: 58, y: 50 } },
      { type: 'summonSquare', position: { x: 59, y: 138 } },
      { type: 'summonSquare', position: { x: 92, y: 138 } },
      { type: 'summonSquare', position: { x: 59, y: 153 } },
    ],
  },
  { level: 4, name: 'boldening blow', actions: { top: CardActions.discard, bottom: CardActions.discard },
    availableEnhancements: [
      { type: 'circle', position: { x: 85, y: 132 } },
      { type: 'square', position: { x: 85, y: 164 } },
    ],
  },
  { level: 5, name: 'explosive epicenter', actions: { top: CardActions.discard, bottom: CardActions.activeLost } },
  { level: 5, name: 'hold the line', actions: { top: CardActions.activeDiscard, bottom: CardActions.activeLost },
    availableEnhancements: [
      { type: 'diamondPlus', position: { x: 82, y: 38 } },
      { type: 'circle', position: { x: 84, y: 125 } },
      { type: 'circle', position: { x: 84, y: 165 } },
    ],
  },
  { level: 6, name: 'barricade', actions: { top: CardActions.activeDiscard, bottom: CardActions.activeLost },
    availableEnhancements: [
      { type: 'summonSquare', position: { x: 59, y: 139 } },
    ],
  },
  { level: 6, name: 'bolstering shout', actions: { top: CardActions.discard, bottom: CardActions.discard },
    availableEnhancements: [
      { type: 'square', position: { x: 75, y: 44 } },
      { type: 'circle', position: { x: 84, y: 136 } },
      { type: 'square', position: { x: 86, y: 158 } },
    ],
  },
  { level: 7, name: 'lead from afar', actions: { top: CardActions.discard, bottom: CardActions.activeLost },
    availableEnhancements: [
      { type: 'diamond', position: { x: 66, y: 45 } },
      { type: 'summonSquare', position: { x: 59, y: 140 } },
      { type: 'summonSquare', position: { x: 92, y: 140 } },
      { type: 'summonSquare', position: { x: 92, y: 155 } },
    ],
  },
  { level: 7, name: 'tri thrust', actions: { top: CardActions.discard, bottom: CardActions.discard },
    availableEnhancements: [
      { type: 'diamond', position: { x: 46, y: 55 } },
      { type: 'circle', position: { x: 86, y: 126 } },
      { type: 'square', position: { x: 67, y: 148 } },
    ],
  },
  { level: 8, name: 'sweeping aid', actions: { top: CardActions.discard, bottom: CardActions.discard },
    availableEnhancements: [
      { type: 'diamond', position: { x: 58, y: 31 } },
      { type: 'circle', position: { x: 85, y: 149 } },
    ],
  },
  { level: 8, name: 'taunting howl', actions: { top: CardActions.activeLost, bottom: CardActions.discard },
    availableEnhancements: [
      { type: 'square', position: { x: 54, y: 39 } },
      { type: 'circle', position: { x: 83, y: 130 } },
      { type: 'square', position: { x: 83, y: 164 } },
    ],
  },
  { level: 9, name: 'hail of spears', actions: { top: CardActions.discard, bottom: CardActions.lose },
    availableEnhancements: [
      { type: 'diamond', position: { x: 66, y: 31 } },
    ],
  },
  { level: 9, name: 'take no prisoners', actions: { top: CardActions.discard, bottom: CardActions.activeLost },
    availableEnhancements: [
      { type: 'summonSquare', position: { x: 59, y: 140 } },
    ],
  },
], bannerSpearPath);
